const Dotenv = require('dotenv-webpack');

module.exports = {
  // ...existing code...
  plugins: [
    // ...existing plugins...
    new Dotenv(),
    // ...existing plugins...
  ],
  // ...existing code...
};
